<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use AppBundle\Entity\BlogPost;
use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;
use Doctrine\ORM\Mapping as ORM;
/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Media extends BaseMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return int $id
     */

    /**
     * @var BlogPost
     *
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\BlogPost", inversedBy="images")
     * @ORM\JoinColumns({
     *     @ORM\JoinColumn(name="Blog", referencedColumnName="id")
     * })
     */
    private $blogpost;

    /**
     * @return BlogPost
     */
    public function getBlogpost()
    {
        return $this->blogpost;
    }

    /**
     * @param BlogPost $blogpost
     */
    public function setBlogpost($blogpost)
    {
        $this->blogpost = $blogpost;
    }
    public function getId()
    {
        return $this->id;
    }
}
